from flask import Flask, jsonify, request
import random
import os

app = Flask(__name__)

# 50+ универсальных H2 для decorewood.ru
H2_POOL = [
    "Преимущества шпона в интерьере",
    "Как выбрать шпон для панелей", 
    "Монтаж шпонированных панелей",
    "Уход за шпон в помещении",
    "Сравнение шпона и ламината",
    "Шпон в офисном дизайне",
    "Цены на шпон 2026",
    "Тренды шпона в 2026",
    "Установка стеновых панелей",
    "Панели в бизнес-центрах",
    "Анти-вандальные панели",
    "Логистика шпонированных панелей",
    "Усадка здания и панели",
    "Подсветка для панелей",
    "Сертификация панелей",
    "Панели в школах и вузах",
    "Обновление БЦ панелями",
    "Черновой ремонт от застройщика",
    "ROI от замены МДФ на шпон",
    "Деформационные швы",
    "Хранение панелей на стройке",
    "Клинг шпонированных панелей",
    "Навигаторы для панелей",
    "Единый оттенок шпона",
    "Панели в ТРЦ зонах отдыха",
    "Шпон в фудкортах",
    "Шпон для гос объектов",
    "Панели с гарантией 10 лет",
    "Расчет стоимости шпона",
    "Доставка по России",
    "Монтаж под ключ",
    "Дизайн-проект бесплатно",
    "Сравнение коллекций",
    "Отзывы клиентов",
    "Кейсы внедрения",
    "Часто задаваемые вопросы",
    "Какой оттенок шпона выбрать под интерьер?",
    "ТОП-5 пород шпона для вашего дома",
    "Светлый или тёмный шпон: что в тренде?",
    "Премиум шпон vs бюджетный: в чём разница?",
    "Натуральная текстура шпона: как выбрать?",
    "Шпон для маленьких помещений: секреты дизайнеров",
    "Качественный шпон: на что смотреть при покупке?",
    "Универсальные породы шпона для любого стиля",
    "Шпон 2026: модные оттенки и текстуры",
    "Как шпон меняет восприятие пространства?",
    "Монтаж шпона на стену: пошаговый план",
    "Скрытый крепёж для шпонированных панелей",
    "Подготовка стен под шпон без штукатурки",
    "Шпон на потолок: особенности установки",
    "Как стыковать панели шпона в углах?",
    "Монтаж шпона в одиночку: реально ли?",
    "Инструменты для идеального монтажа шпона",
    "Шпон на неровные стены: как выровнять?",
    "Сколько клея нужно на 1 стену шпоном?",
    "Финишная обработка шпонированных панелей",
    "Шпон в гостиной: 5 удачных решений",
    "Акцентная стена шпоном: где лучше всего?",
    "Шпон в спальне: уют без перегрузки",
    "Как шпон преображает коридор?",
    "Шпон + обои: удачное зонирование",
    "Студия-однушка со шпоном: визуальное увеличение",
    "Шпон в кухне: практичные идеи",
    "Детская со шпоном: безопасность и стиль",
    "Шпон в ванной: где можно применять?",
    "Преображение хрущёвки шпонированными стенами",
    "Реальная стоимость отделки шпоном 1 м²",
    "Шпон vs краска vs обои: сравнение цен",
    "Сколько экономит шпон перед массивом?",
    "Бюджет на отделку стены шпоном: расчёт",
    "Цены на шпон 2026: что подорожает?",
    "Шпон эконом-класса с премиум видом",
    "Смета на монтаж шпонированных панелей",
    "Где купить шпон дешевле без потери качества?",
    "Сколько стоит покраска шпона после монтажа?",
    "Оптовая закупка шпона: где выгодно?",
    "Уход за шпоном: что можно, а что нельзя",
    "Как чистить шпонированные панели?",
    "Шпон и домашние животные: совместимость",
    "Что делать при царапинах на шпоне?",
    "Защита шпона от солнца и выцветания",
    "Шпон в доме с маленькими детьми",
    "Как продлить срок службы шпонированных стен?",
    "Чем протирать шпон: средства и тряпки",
    "Шпон после 5 лет: реальный опыт",
    "Антивандальный шпон: миф или реальность?"
]

@app.route('/random-h2')
def random_h2():
    count = int(request.args.get('count', 7))
    available = min(count, len(H2_POOL))
    h2_list = random.sample(H2_POOL, available)
    
    return jsonify({
        "h2s": h2_list,
        "count": len(h2_list)
    })

@app.route('/')
def home():
    return "Randomizer OK. /random-h2?count=7"

KEYWORDS_DB = [
    "шпонированные стеновые панели",
    "МДФ панели для стен",
    "отделка стен шпоном",
    "стеновые панели шпон дуб",
    "купить шпонированные панели",
    "монтаж МДФ панелей",
    "шпонированные панели цена",
    "панели из шпона орех",
    "3D фрезеровка стеновых панелей",
    "влагостойкие панели МДФ",
    "стеновые панели для гостиной",
    "шпон дуб натуральный",
    "отделка шпоном кухня",
    "МДФ панели купить",
    "шпонированные панели Москва",
    "панели шпон для прихожей",
    "фото интерьеров шпон",
    "тренды отделки стен 2026",
    "шпонированные панели спальня",
    "акцентная стена шпон",
    "стеновые панели 3D",
    "шпон орех американский",
    "монтаж панелей на рейку",
    "шпонированный МДФ цена м2",
    "панели для внутренней отделки",
    "шпон vs ЛДСП сравнение",
    "стеновые панели под заказ",
    "отделка стен панелями",
    "шпонированные панели отзывы",
    "панели МДФ влагостойкие",
    "шпон для стен цена",
    "3D панели МДФ фрезеровка",
    "стеновые панели каталог",
    "шпонированные панели бренды",
    "МДФ панели для офиса",
    "шпон натуральный vs экошпон",
    "панели шпон для потолка",
    "отделка коридора панелями",
    "шпонированные панели Wallhof",
    "стеновые панели Bleek",
    "шпон дуб морёный",
    "панели для кухни шпон",
    "МДФ панели размеры",
    "шпонированные панели Алплит",
    "стеновые панели Волховец",
    "шпон ясень белый",
    "панели МДФ под камень",
    "отделка стен рейками",
    "шпонированные панели санузел",
    "3D панели для ТВ зоны",
    "стеновые панели под покраску",
    "шпон бук цена",
    "панели для детской комнаты",
    "МДФ панели под заказ",
    "шпонированные панели Хрущёвка",
    "отделка ниш шпоном",
    "стеновые панели с подсветкой",
    "шпон венге панели",
    "панели МДФ для потолка",
    "шпонированные панели loft",
    "стеновые панели классика",
    "3D панели геометрия",
    "шпон для акцентной стены",
    "МДФ панели белые",
    "отделка стен минимализм",
    "шпонированные панели неоклассика",
    "панели шпон сканди стиль",
    "стеновые панели с фрезеровкой",
    "шпон палисандр панели",
    "МДФ панели для балкона",
    "шпонированные панели ламинат",
    "стеновые панели HPL",
    "отделка стен пробковыми панелями",
    "шпон сапели панели",
    "панели МДФ текстура",
    "шпонированные панели 6мм",
    "стеновые панели 8мм",
    "3D панели для спальни",
    "шпон для потолка цена",
    "МДФ панели финиш",
    "отделка стен гипсокартоном",
    "шпонированные панели тонировка",
    "панели шпон для ванной",
    "стеновые панели антиванил",
    "шпон мербау панели",
    "МДФ панели тонированные",
    "шпонированные панели светлые",
    "отделка стен темным шпоном",
    "3D панели для кухни",
    "стеновые панели с LED",
    "шпон зебрано панели",
    "панели МДФ для лоджии",
    "шпонированные панели матовые",
    "отделка стен глянцевым шпоном",
    "стеновые панели с зеркалами",
    "шпон эвкалипт панели",
    "МДФ панели с перфорацией",
    "шпонированные панели радиальные",
    "3D панели для коридора",
    "стеновые панели тангенциальный шпон",
    "декоративные панели из шпона",
    "декор интерьера", 
    "художественная техника декупаж",
    "природные мотивы в декоре интерьера",
    "лист мдф",
    "шпонированный мдф",
    "декор на стену",
    "мдф плита",
    "фасадный декор",
    "шпон",
    "шпон это"
    "фальшпанель"
    "шпон что это",
    "шпонированный мдф",
    "руспанель что это",
    "мдф плита",
    "экошпон что это",
    "экошпон это",
    "что такое шпон в мебели",
    "орех шпонирование мдф",
    "радиальный шпон",
    "мдф шпонированный дубом",
    "орех ф шпонированное мдф",
    "фибропанели",
    "натуральный шпон",
    "шпон дуба что это"
]

@app.route("/random-keywords")
def get_random_keywords():
    # Рандомно 5–7 ключей (без повторений)
    count = random.randint(5, 7)
    random_keywords = random.sample(KEYWORDS_DB, count)
    
    return jsonify({
        "keywords": random_keywords,
        "main_keyword": random_keywords[0],  # Главный ключ
        "secondary": random_keywords[1:]     # Остальные
    })

# Только ссылки (читабельные URL)
INTERNAL_ARTICLES = [
    "https://blog-decorewood.ru/7-oshibok-pri-vybore-shponirovannyh-panelej-dlya-doma-i-kak-ih-izbezhat/",
    "https://blog-decorewood.ru/tyoplyj-interer-bez-massiva-kak-shpon-ekonomit-byudzhet/",
    "https://blog-decorewood.ru/shponirovannye-paneli-v-malenkoj-kvartire-kak-ne-utyazhelit-prostranstvo/",
    "https://blog-decorewood.ru/kak-podobrat-czvet-shpona-pod-sushhestvuyushhuyu-mebel-i-dveri/",
    "https://blog-decorewood.ru/shponirovannyj-mdf-v-prihozhej-praktichnost-protiv-gryazi-i-udarov/",
    "https://blog-decorewood.ru/mozhno-li-ispolzovat-shponirovannye-paneli-v-kuhne-i-zone-fartuka/",
    "https://blog-decorewood.ru/shpon-v-spalne-idei-myagkih-i-uyutnyh-stenovyh-panelej/",
    "https://blog-decorewood.ru/akczentnaya-stena-iz-shpona-za-televizorom-prakticheskie-sovety/",
    "https://blog-decorewood.ru/kak-sochetat-shponirovannye-paneli-i-pokrasku-sten-v-odnoj-komnate/",
    "https://blog-decorewood.ru/naturalnyj-shpon-vs-ekoshpon-chto-realno-vidit-glaz-i-chuvstvuet-ruka/",
    "https://blog-decorewood.ru/uhod-za-shponirovannymi-panelyami-chem-protirat-i-chego-boyatsya/",
    "https://blog-decorewood.ru/paneli-iz-shpona-v-detskoj-ekologichno-li-eto-i-naskolko-bezopasno/",
    "https://blog-decorewood.ru/kak-vizualno-podnyat-potolok-s-pomoshhyu-vertikalnyh-shponirovannyh-reek/",
    "https://blog-decorewood.ru/zonirovanie-studii-shponirovannymi-panelyami-idei-planirovok/",
    "https://blog-decorewood.ru/shponirovannyj-mdf-i-shumoizolyacziya-realno-li-stanet-tishe/",
    "https://blog-decorewood.ru/skolko-stoit-odet-odnu-stenu-v-shpon-razbor-smety-na-primere/",
    "https://blog-decorewood.ru/kak-ne-oshibitsya-s-tonom-dubovogo-shpona-v-raznyh-istochnikah-sveta/",
    "https://blog-decorewood.ru/modnyj-trend-ritmichnye-rejki-iz-shpona-vmesto-goloj-steny/",
    "https://blog-decorewood.ru/shponirovannye-paneli-v-koridore-hrushhyovki-vizualnoe-rasshirenie-prostranstva/",
    "https://blog-decorewood.ru/kak-zakryt-nerovnye-steny-shponom-i-izbezhat-mokryh-proczessov/",
    "https://blog-decorewood.ru/mozhno-li-montirovat-shponirovannye-paneli-svoimi-rukami/",
    "https://blog-decorewood.ru/pochemu-shponirovannye-paneli-luchshe-ldsp-dlya-sten-v-zhilyh-komnatah/",
    "https://blog-decorewood.ru/shpon-i-tyoplyj-skandinavskij-stil-idei-dlya-tipovoj-dvushki/",
    "https://blog-decorewood.ru/kak-sdelat-dorogoj-interer-bez-dorogostoyashhih-materialov-za-schyot-shpona/",
    "https://blog-decorewood.ru/shponirovannye-paneli-v-zagorodnom-dome-zashhita-sten-i-atmosfernost/",
    "https://blog-decorewood.ru/sovmeshhenie-kamnya-i-shpona-na-stenah-udachnye-pary-materialov/",
    "https://blog-decorewood.ru/chastye-voprosy-poczarapali-shpon-chto-delat-i-kak-remontirovat/",
    "https://blog-decorewood.ru/shponirovannye-stenovye-paneli-i-domashnie-zhivotnye-ustojchivost-k-kogtyam/",
    "https://blog-decorewood.ru/kak-vybrat-teksturu-dubovogo-shpona-radial-tangens-rustik/",
    "https://blog-decorewood.ru/paneli-v-shpone-oreha-dlya-kakih-intererov-etot-czvet-realno-zahodit/",
    "https://blog-decorewood.ru/kak-pravilno-podsvetit-stenovye-paneli-iz-shpona-chtoby-podcherknut-teksturu/",
    "https://blog-decorewood.ru/oshibki-montazha-shponirovannyh-panelej-kotorye-vidny-cherez-polgoda/",
    "https://blog-decorewood.ru/shponirovannye-paneli-i-natyazhnye-potolki-kak-gramotno-sostykovat/",
    "https://blog-decorewood.ru/paneli-iz-shpona-v-sanuzle-gde-mozhno-a-gde-nelzya/",
    "https://blog-decorewood.ru/kak-shponirovannye-paneli-pomogayut-skryt-dveri-i-sdelat-nevidimki/",
    "https://blog-decorewood.ru/paneli-na-mdf-ili-fanere-chto-luchshe-dlya-kvartiry/",
    "https://blog-decorewood.ru/kak-shponirovannye-steny-vliyayut-na-vospriyatie-stoimosti-zhilya-pokupatelem/",
    "https://blog-decorewood.ru/trendy-2025-kakie-ottenki-shpona-chashhe-vsego-vybirayut-dlya-kvartir/",
    "https://blog-decorewood.ru/vintazh-ili-sovremennost-kak-sochetat-shpon-s-antikvariatom-i-minimalizmom/",
    "https://blog-decorewood.ru/shponirovannye-paneli-i-vstroennaya-mebel-kak-sobrat-vsyo-v-odnu-kompozicziyu/",
    "https://blog-decorewood.ru/kak-podgotovit-stenu-pod-montazh-shponirovannyh-panelej-v-starom-fonde/",
    "https://blog-decorewood.ru/shpon-i-umnyj-dom-kuda-pryatat-provodku-i-osveshhenie-v-panelyah/",
    "https://blog-decorewood.ru/5-mifov-o-shponirovannyh-stenah-kotorye-meshayut-sdelat-krasivyj-interer/",
    "https://blog-decorewood.ru/kak-vybrat-postavshhika-shponirovannyh-panelej-dlya-kvartiry-chek-list/",
    "https://blog-decorewood.ru/realnye-sroki-proizvodstva-i-montazha-stenovyh-panelej-iz-shpona/",
    "https://blog-decorewood.ru/shponirovannyj-mdf-kak-investicziya-naskolko-on-perezhivaet-kosmeticheskij-remont/",
    "https://blog-decorewood.ru/paneli-iz-shpona-v-arenduemoj-kvartire-stoit-li-vkladyvatsya/",
    "https://blog-decorewood.ru/kak-sohranit-shpon-idealnym-esli-v-dome-malenkie-deti/",
    "https://blog-decorewood.ru/kak-gramotno-ispolzovat-shponirovannye-paneli-v-konczepczii-interera-bez-peregruza/",
    "https://blog-decorewood.ru/kombinacziya-shpona-i-okraski-priyomy-dlya-akczentnyh-sten-i-nish/",
    "https://blog-decorewood.ru/shponirovannyj-mdf-vs-massiv-v-proekte-argumenty-dlya-klienta-i-byudzheta/",
    "https://blog-decorewood.ru/kak-prezentovat-ideyu-shponirovannyh-panelej-zakazchiku-kotoryj-boitsya-dereva/",
    "https://blog-decorewood.ru/nyuansy-uzlov-stykovka-shponirovannyh-panelej-s-otkosami-i-dvernymi-korobkami/",
    "https://blog-decorewood.ru/prorabotka-modulej-setka-fasadov-panelej-i-ritm-risunka-shpona/",
    "https://blog-decorewood.ru/vertikalnye-rejki-vs-gladkie-paneli-kogda-chto-rabotaet-luchshe-v-proekte/",
    "https://blog-decorewood.ru/rabota-s-rekonstruirovannym-shponom-plyusy-po-czvetu-i-minusy-po-zhivosti/",
    "https://blog-decorewood.ru/kak-uchityvat-fakturu-shpona-v-vizualizacziyah-chtoby-ne-razocharovat-klienta/",
    "https://blog-decorewood.ru/vybor-tolshhiny-mdf-i-podlozhki-pod-zadachi-konkretnogo-obekta/",
    "https://blog-decorewood.ru/zadachi-dlya-podryadchika-kak-pravilno-sformulirovat-tz-na-shponirovannye-paneli/",
    "https://blog-decorewood.ru/chastye-oshibki-v-tehzadanii-na-paneli-kotorye-privodyat-k-pererabotkam/",
    "https://blog-decorewood.ru/shponirovannye-paneli-v-obshhestvennyh-intererah-normy-po-pozharnoj-bezopasnosti-km1-i-dr/",
    "https://blog-decorewood.ru/kak-ispolzovat-shponirovannye-paneli-dlya-akustiki-v-ofisah-i-peregovornyh/",
    "https://blog-decorewood.ru/dekorativnye-paneli-iz-shpona-kak-instrument-zonirovaniya-open-space/",
    "https://blog-decorewood.ru/sczenarii-podsvetki-skrytye-profili-i-linejnye-svetilniki-v-shponirovannyh-stenah/",
    "https://blog-decorewood.ru/prorabotka-primykanij-plintusa-potolki-vstroennye-shkafy-k-panelyam/",
    "https://blog-decorewood.ru/skrytye-dveri-v-shponirovannyh-panelyah-konstruktiv-i-nyuansy-furnitury/",
    "https://blog-decorewood.ru/ispolzovanie-shpona-v-koridorah-i-lobbi-zhilyh-kompleksov-iznosostojkost-i-antivandalnost/",
    "https://blog-decorewood.ru/kak-vybrat-porodu-shpona-pod-stil-minimalizm-neoklassika-mid-century/",
    "https://blog-decorewood.ru/shponirovannye-paneli-v-horeca-kejsy-barov-restoranov-lobbi-otelej/",
    "https://blog-decorewood.ru/ekologichnost-i-sertifikaty-kak-obyasnit-zakazchiku-polzu-shpona-protiv-pvh/",
    "https://blog-decorewood.ru/kak-uchityvat-linii-shpona-pri-rasstanovke-mebeli-i-art-obektov/",
    "https://blog-decorewood.ru/sozdanie-edinogo-koroba-iz-shpona-steny-dveri-shkafy/",
    "https://blog-decorewood.ru/shponirovannye-paneli-i-akusticheskie-rejki-sochetaemost-v-odnom-proekte/",
    "https://blog-decorewood.ru/uchet-inzhenerii-revizionnye-lyuki-i-dostup-k-kommunikacziyam-v-panelyah/",
    "https://blog-decorewood.ru/kak-ispolzovat-shponirovannyj-mdf-v-potolochnyh-resheniyah-bez-oshhushheniya-sauny/",
    "https://blog-decorewood.ru/modelirovanie-panelej-v-revit-archicad-kak-oblegchit-sebe-zhizn/",
    "https://blog-decorewood.ru/tipovye-karty-raskroya-shponirovannyh-panelej-i-vliyanie-na-byudzhet-proekta/",
    "https://blog-decorewood.ru/kak-obyasnit-zastrojshhiku-investoru-roi-ot-primeneniya-shpona-v-obshhestvennyh-zonah/",
    "https://blog-decorewood.ru/kejsy-transformacziya-tipovogo-belogo-ofisa-v-premialnoe-prostranstvo-za-schyot-shpona/",
    "https://blog-decorewood.ru/oshibki-v-podbore-ottenka-shpona-pod-iskusstvennyj-svet-3000k-4000k/",
    "https://blog-decorewood.ru/kak-rabotat-so-shponom-v-interere-s-panoramnym-ostekleniem-i-yarkim-solnczem/",
    "https://blog-decorewood.ru/sopryazhenie-shponirovannyh-panelej-s-kamnem-betonom-i-metallom-v-premialnom-segmente/",
    "https://blog-decorewood.ru/shpon-vs-dekorativnaya-shtukaturka-argumenty-v-polzu-gibridnyh-reshenij/",
    "https://blog-decorewood.ru/kak-vpisat-shponirovannye-paneli-v-byudzhetnyj-proekt-bez-poteri-vizuala/",
    "https://blog-decorewood.ru/sczenarij-ispolzovanie-shponirovannyh-panelej-v-shourume-ofise-samoj-dizajn-studii/",
    "https://blog-decorewood.ru/kak-dokumentirovat-uzly-i-speczifikaczii-po-shponu-v-rabochem-proekte/",
    "https://blog-decorewood.ru/avtorskij-nadzor-po-shponirovannym-panelyam-chek-list-vyezda-na-obekt/",
    "https://blog-decorewood.ru/kak-podgotovit-portfolio-s-proektami-so-shponirovannymi-panelyami-chtoby-prodavat-bolshe-takih-reshenij/",
    "https://blog-decorewood.ru/psihologiya-vospriyatiya-dereva-v-interere-kak-ispolzovat-shpon-dlya-dorogogo-spokojstviya/",
    "https://blog-decorewood.ru/shponirovannye-paneli-v-kommercheskih-intererah-s-vysokoj-prohodimostyu-lajfhaki-po-iznosostojkosti/",
    "https://blog-decorewood.ru/kak-rabotat-s-postavshhikom-shpona-obrazczy-makety-soglasovanie-napravleniya-volokon/",
    "https://blog-decorewood.ru/trendy-2025-2026-po-shponirovannym-panelyam-3d-relef-geometriya-kombinirovannye-materialy/",
    "https://blog-decorewood.ru/kejsy-do-posle-kak-odna-shponirovannaya-stena-vliyaet-na-vospriyatie-interera/",
    "https://blog-decorewood.ru/shponirovannye-paneli-i-biofilnyj-dizajn-kak-sdelat-interer-zhivym/",
    "https://blog-decorewood.ru/kak-argumentirovat-primenenie-shpona-v-tendere-po-sravneniyu-s-drugimi-materialami/",
    "https://blog-decorewood.ru/tipichnye-voprosy-zakazchika-po-shponu-i-gotovye-otvety-dizajnera/",
    "https://blog-decorewood.ru/glubokie-matovye-pokrytiya-i-otkrytaya-pora-shpona-kak-eto-vliyaet-na-kartinku/",
    "https://blog-decorewood.ru/rabochie-sczenarii-kogda-ispolzovat-shpon-kak-glavnyj-material-proekta-a-kogda-tolko-akczentno/",
    "https://blog-decorewood.ru/pochemu-shponirovannye-paneli-povyshayut-vosprinimaemuyu-stoimost-zhk-bez-kratnogo-rosta-smety/",
    "https://blog-decorewood.ru/shpon-v-obshhestvennyh-zonah-kak-prodat-dorogoj-podezd-pokupatelyu-kvartiry/",
    "https://blog-decorewood.ru/klass-pozharnoj-bezopasnosti-shponirovannyh-panelej-i-trebovaniya-k-obshhestvennym-intereram/",
    "https://blog-decorewood.ru/kak-shponirovannye-paneli-pomogayut-vydelit-proekt-na-konkurentnom-rynke-novostroek/",
    "https://blog-decorewood.ru/ekonomika-shponirovannyj-mdf-protiv-massiva-i-naturalnogo-kamnya-v-zonah-obshhego-polzovaniya/",
    "https://blog-decorewood.ru/tipovye-resheniya-iz-shpona-dlya-vhodnyh-grupp-koridorov-i-liftovyh-hollov/",
    "https://blog-decorewood.ru/kak-ispolzovat-shponirovannye-paneli-dlya-brendirovaniya-zhilogo-kompleksa/",
    "https://blog-decorewood.ru/ustojchivost-k-vandalizmu-chem-pokryvat-shpon-v-mestah-s-vysokoj-nagruzkoj/",
    "https://blog-decorewood.ru/mdf-paneli/",
    "https://blog-decorewood.ru/stenovye-paneli-mdf/",
    "https://blog-decorewood.ru/mdf-paneli-dlya-sten/",
    "https://blog-decorewood.ru/mdf-paneli-kupit/",
    "https://blog-decorewood.ru/otdelka-mdf-panelyami/",
    "https://blog-decorewood.ru/vnutrennyaya-mdf-panel-stilnoe-i-praktichnoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/vnutrennyaya-otdelka-paneli-mdf-stilnoe-reshenie-dlya-vashego-interera/",
    "https://blog-decorewood.ru/shponirovannye-paneli-stilnoe-i-praktichnoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/shponirovannye-stenovye-paneli-stilnoe-i-sovremennoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/shponirovannye-paneli-mdf-stilnoe-i-sovremennoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/shponirovannye-paneli-kupit-luchshie-varianty-dlya-stilnogo-interera/",
    "https://blog-decorewood.ru/montazh-shponirovannyh-panelej-poshagovaya-instrukcziya-i-sovety-ekspertov/",
    "https://blog-decorewood.ru/dekorativnye-stenovye-paneli-stilnoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/dekorativnaya-panel-vnutrennyaya-stilnoe-reshenie-dlya-sovremennogo-interera/",
    "https://blog-decorewood.ru/dekorativnye-paneli-dlya-sten-trendy-vidy-i-idei-oformleniya/",
    "https://blog-decorewood.ru/dekorativnye-paneli-dlya-vnutrennej-otdelki-sten-idei-i-sovety-dizajnerov/",
    "https://blog-decorewood.ru/panel-dekorativnaya-mdf-stilnoe-reshenie-dlya-sovremennogo-interera/",
    "https://blog-decorewood.ru/dekorativnye-paneli-dlya-sten-stilnoe-reshenie-dlya-sovremennogo-interera/",
    "https://blog-decorewood.ru/otdelka-sten-panelyami-mdf-stilnoe-i-praktichnoe-reshenie-dlya-doma-2/",
    "https://blog-decorewood.ru/paneli-mdf-dlya-sten-dlya-vnutrennej-otdelki-stil-i-praktichnost/",
    "https://blog-decorewood.ru/paneli-sten-vnutrennej-otdelki-mdf-stilnoe-i-praktichnoe-reshenie/",
    "https://blog-decorewood.ru/mdf-paneli-dlya-sten-kupit-luchshie-varianty-po-vygodnoj-czene/",
    "https://blog-decorewood.ru/stenovye-paneli-mdf-kupit-po-vygodnoj-czene-s-dostavkoj/",
    "https://blog-decorewood.ru/kak-krepit-paneli-mdf-poshagovaya-instrukcziya-dlya-nachinayushhih/",
    "https://blog-decorewood.ru/panel-mdf-pod-kamen-stilnoe-i-dostupnoe-oformlenie-interera/",
    "https://blog-decorewood.ru/panel-mdf-dub-stilnoe-i-praktichnoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/reechnye-mdf-paneli-stilnoe-i-sovremennoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/mdf-paneli-foto-stilnye-idei-otdelki-dlya-sovremennogo-interera/",
    "https://blog-decorewood.ru/montazh-panelej-mdf-poshagovaya-instrukcziya-dlya-idealnoj-otdelki/",
    "https://blog-decorewood.ru/mdf-paneli-czena-kak-vybrat-i-kupit-vygodno-dlya-interera/",
    "https://blog-decorewood.ru/panel-mdf-belaya-stilnoe-reshenie-dlya-sovremennogo-interera/",
    "https://blog-decorewood.ru/kakie-paneli-mdf-vybrat-vidy-harakteristiki-i-sovety-po-primeneniyu/",
    "https://blog-decorewood.ru/mdf-paneli-dlya-kuhni-stilnoe-i-praktichnoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/panel-mdf-razmery-kak-vybrat-optimalnyj-variant-dlya-otdelki/",
    "https://blog-decorewood.ru/kupit-panel-mdf-dlya-otdelki-vygodnye-czeny-i-udobnyj-vybor/",
    "https://blog-decorewood.ru/kupit-panel-mdf-dlya-vnutrennej-otdelki-luchshie-czeny-i-kachestvo/",
    "https://blog-decorewood.ru/mdf-panel-na-vhodnuyu-dver-stilnaya-i-praktichnaya-otdelka/",
    "https://blog-decorewood.ru/mdf-panel-na-vhodnuyu-dver-obnovite-interer-stilno-i-nedorogo/",
    "https://blog-decorewood.ru/mdf-paneli-dlya-potolka-stilnoe-i-praktichnoe-oformlenie-interera/",
    "https://blog-decorewood.ru/otdelka-stenovymi-panelyami-mdf-stilnoe-i-dostupnoe-reshenie-dlya-doma/",
    "https://blog-decorewood.ru/paneli-mdf-svoimi-rukami-poshagovaya-instrukcziya-po-ustanovke/",
    "https://blog-decorewood.ru/stenovye-paneli-mdf-dlya-vnutrennej-otdelki-sovremennoe-reshenie/",
    "https://blog-decorewood.ru/stenovye-paneli-mdf-dlya-vnutrennej-otdelki-stil-i-praktichnost/",
    "https://blog-decorewood.ru/kak-krepit-paneli-mdf-k-stene-poshagovaya-instrukcziya-dlya-novichkov/",
    "https://blog-decorewood.ru/kupit-mdf-paneli-dlya-vnutrennih-sten-luchshie-czeny-i-dostavka/",
    "https://blog-decorewood.ru/otdelka-sten-panelyami-mdf-kupit-stilnoe-reshenie-dlya-vashego-doma/",
    "https://blog-decorewood.ru/paneli-iz-shpona-dub-stilnoe-i-praktichnoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/paneli-iz-shpona-yasen-stilnoe-i-sovremennoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/paneli-iz-shpona-oreh-stilnoe-i-dolgovechnoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/paneli-iz-shpona-buk-stilnoe-i-dolgovechnoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/paneli-iz-shpona-venge-stilnoe-reshenie-dlya-sovremennogo-interera/",
    "https://blog-decorewood.ru/paneli-iz-shpona-zebrano-elegantnyj-akczent-v-sovremennom-interere-2/",
    "https://blog-decorewood.ru/paneli-iz-shpona-merbau-stilnoe-i-dolgovechnoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/paneli-iz-shpona-palisandr-elegantnaya-otdelka-interera/",
    "https://blog-decorewood.ru/paneli-iz-shpona-sapele-elegantnoe-reshenie-dlya-stilnogo-interera/",
    "https://blog-decorewood.ru/paneli-iz-shpona-dub-naturalnyj-stil-i-elegantnost-v-interere/",
    "https://blog-decorewood.ru/paneli-iz-shpona-dub-moryonyj-stilnoe-reshenie-dlya-sovremennogo-interera/",
    "https://blog-decorewood.ru/paneli-iz-shpona-oreh-amerikanskij-elegantnyj-vybor-dlya-interera/",
    "https://blog-decorewood.ru/paneli-iz-shpona-oreh-evropejskij-stil-i-elegantnost-v-interere/",
    "https://blog-decorewood.ru/paneli-iz-shpona-yasen-belyj-stil-i-prirodnaya-elegantnost-v-interere/",
    "https://blog-decorewood.ru/mdf-paneli-dlya-dverej-stilnoe-i-praktichnoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/kupit-mdf-paneli-dlya-sten-vnutrennej-otdelki-po-vygodnoj-czene/",
    "https://blog-decorewood.ru/paneli-mdf-vlagostojkie-nadyozhnaya-otdelka-dlya-kuhni-i-vannoj/",
    "https://blog-decorewood.ru/mdf-paneli-dlya-doma-stilnaya-otdelka-sten-i-vygodnoe-reshenie/",
    "https://blog-decorewood.ru/listovaya-panel-mdf-idealnoe-reshenie-dlya-otdelki-interera/",
    "https://blog-decorewood.ru/reechnye-stenovye-paneli-mdf-stilnoe-i-sovremennoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/populyarnye-czveta-mdf-panelej-dlya-sovremennogo-interera/",
    "https://blog-decorewood.ru/tolshhina-mdf-panelej-optimalnyj-vybor-dlya-otdelki-i-mebeli/",
    "https://blog-decorewood.ru/luchshie-mdf-paneli-dlya-interera-obzor-vidy-i-sovety-po-vyboru/",
    "https://blog-decorewood.ru/otdelka-komnaty-panelyami-mdf-sovremennye-idei-i-sovety-dizajnerov/",
    "https://blog-decorewood.ru/shponirovannye-paneli-v-ofisnyh-czentrah-uvelichte-arendnuyu-stavku-otdelkoj/",
    "https://blog-decorewood.ru/sroki-proizvodstva-i-montazha-shponirovannyh-panelej-na-krupnom-obekte/",
    "https://blog-decorewood.ru/kak-standartizirovat-uzly-shponirovannyh-panelej-v-tipovyh-proektah/",
    "https://blog-decorewood.ru/oshibki-na-etape-tendernoj-dokumentaczii-po-shponu-i-kak-ih-izbezhat/",
    "https://blog-decorewood.ru/kak-vybirat-postavshhika-shponirovannyh-panelej-dlya-setevogo-developera/",
    "https://blog-decorewood.ru/vliyanie-shpona-na-akustiku-mop-kak-povysit-komfort-i-uyut-pomeshhenij/",
    "https://blog-decorewood.ru/shpon-i-esg-povestka-kak-derevyannye-paneli-usilivayut-zelyonyj-imidzh-proekta/",
    "https://blog-decorewood.ru/primenenie-shponirovannyh-panelej-v-apart-otelyah-i-servisnyh-rezidencziyah/",
    "https://blog-decorewood.ru/kak-ispolzovat-shpon-dlya-zon-resepshen-i-kovorkingov-v-zhk/",
    "https://blog-decorewood.ru/sczenarij-otdelki-chernovoj-remont-ot-zastrojshhika-shponirovannye-paneli/",
    "https://blog-decorewood.ru/logistika-i-hranenie-shponirovannyh-panelej-na-strojploshhadke-sovety-profi/",
    "https://blog-decorewood.ru/kak-uchityvat-usadku-zdaniya-i-deformaczionnye-shvy-pri-montazhe-shponirovannyh-panelej/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-albero-310s-stil-i-uyut-v-kazhdom-interere/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-albero-1294m-stil-i-uyut-dlya-lyubogo-interera/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-albero-5aa-s-stil-i-kachestvo-dlya-interera/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-albero-05c-stil-i-kachestvo-dlya-vashego-interera/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-espresso-021c-stil-i-uyut-v-vashem-interere/",
    "https://blog-decorewood.ru/primery-uspeshnyh-biznes-czentrov-gde-shponirovannye-paneli-formiruyut-brend/",
    "https://blog-decorewood.ru/roi-ot-zameny-materialov-mop-na-shponirovannye-paneli-prostaya-model-raschyota/",
    "https://blog-decorewood.ru/shponirovannye-paneli-i-navigacziya-sovremennye-resheniya-s-podsvetkoj/",
    "https://blog-decorewood.ru/kak-dobitsya-edinoobraziya-ottenka-shpona-na-bolshih-obyomah-postavok/",
    "https://blog-decorewood.ru/trebovaniya-k-dokumentaczii-i-sertifikaczii-shponirovannyh-panelej-dlya-gos-obektov/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-espresso-498s-stil-i-kachestvo-dlya-vashego-interera/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-espresso-2781c-idealnyj-vybor-dlya-vashego-interera/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-espresso-35m-idealnoe-reshenie-dlya-interera/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-espresso-2293s-idealnoe-reshenie-dlya-vashego-interera/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-espresso-360m-elegantnost-i-kachestvo-dlya-vashego-interera/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-espresso-moon-v-stil-i-elegantnost-v-interere/",
    "https://blog-decorewood.ru/shponirovannye-paneli-v-shkolah-i-vuzah-estetika-i-antivandalnost/",
    "https://blog-decorewood.ru/ispolzovanie-shpona-v-trcz-kak-sozdat-uyutnye-zony-otdyha-i-fudkorty/",
    "https://blog-decorewood.ru/kak-paneli-iz-shpona-bystro-obnovyat-imidzh-starogo-bcz-bez-remonta/",
    "https://blog-decorewood.ru/effektivnaya-ekspluatacziya-shponirovannyh-panelej-pri-klininge/",
    "https://blog-decorewood.ru/effektivnaya-ekspluatacziya-shponirovannyh-panelej-pri-klininge-2/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-buk-eko-elegantnost-i-uyut-v-vashem-interere/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-yasen-stil-i-uyut-v-kazhdom-dome/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-oreh-amerikanskij-elegantnost-i-stil-v-interere/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-evkalipt-frisse-stil-i-uyut-v-vashem-interere/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-palisandr-santos-elegantnost-i-uyut-v-interere/",
    "https://blog-decorewood.ru/standartizacziya-czvetovyh-reshenij-shpona-klyuch-k-uspehu-developerskih-proektov/",
    "https://blog-decorewood.ru/shponirovannye-paneli-idealnoe-reshenie-dlya-zvukoizolyaczii-koridorov-i-zalov/",
    "https://blog-decorewood.ru/chto-takoe-naturalnyj-shpon-i-kak-ego-proizvodyat-uznajte-vse-tonkosti/",
    "https://blog-decorewood.ru/kak-vklyuchit-shponirovannye-paneli-v-marketing-i-vizualizacziyu-proekta/",
    "https://blog-decorewood.ru/kak-minimizirovat-riski-pri-rabote-s-malym-proizvoditelem-shponirovannyh-panelej/",
    "https://blog-decorewood.ru/modulnye-shponirovannye-sistemy-uskorte-otdelku-i-minimizirujte-oshibki/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-espresso-149s-idealnyj-vybor-dlya-vashego-interera/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-duna-500c-idealnoe-reshenie-dlya-vashego-interera/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-duna-605s-idealnyj-vybor-dlya-vashego-interera/",
    "https://blog-decorewood.ru/stenovye-paneli-iz-shpona-duna-624c-idealnoe-reshenie-dlya-vashego-interera/",
    "https://blog-decorewood.ru/kak-organizovat-avtorskij-kontrol-kachestva-shpona-na-proizvodstve-sovety-ekspertov/",
    "https://blog-decorewood.ru/sovremennye-sczenarii-fit-out-kak-shpon-preobrazuet-ofisy-klassa-a/",
    "https://blog-decorewood.ru/sovmeshhenie-korporativnogo-stilya-arendatora-i-otdelki-shponom-ot-developera/",
    "https://blog-decorewood.ru/garantijnye-obyazatelstva-po-shponirovannym-panelyam-osnovnye-aspekty-v-dogovorah-s-podryadchikami/",
    "https://blog-decorewood.ru/shpon-v-interere-kak-povysit-likvidnost-nedvizhimogo-obekta/"
]

@app.route("/")
def home():
    return jsonify({"status": "OK", "endpoint": "/random-links"})

@app.route("/random-links")
def get_random_links():
    random_links = random.sample(INTERNAL_ARTICLES, 3)
    return jsonify({"links": random_links})

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
